title: Talk am Pegel
short_title: Talk am Pegel
description: Die neue Talk-Reihe in Neuss.
baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: events
    values:
      layout: event
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
  events:
    output: true
    permalink: "/talks/:path/"
future: true
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
