<?php

/**
 * @method static boolean accepted($value)
 * @method static boolean alpha($value, $unicode)
 * @method static boolean alphanum($value, $unicode)
 * @method static boolean between($value, $min, $max)
 * @method static boolean contains($value, $needle)
 * @method static boolean date($value, $operator, $test)
 * @method static boolean denied($value)
 * @method static boolean different($value, $other, $strict)
 * @method static boolean email($value)
 * @method static boolean endsWith($value, $end)
 * @method static boolean filename($value)
 * @method static boolean in($value, $in, $strict)
 * @method static boolean integer($value, $strict)
 * @method static boolean ip($value)
 * @method static boolean less($value, $max)
 * @method static boolean match($value, $pattern)
 * @method static boolean max($value, $max)
 * @method static boolean min($value, $min)
 * @method static boolean maxLength($value, $max)
 * @method static boolean minLength($value, $min)
 * @method static boolean maxWords($value, $max)
 * @method static boolean minWords($value, $min)
 * @method static boolean more($value, $min)
 * @method static boolean notContains($value, $needle)
 * @method static boolean notIn($value, $notIn)
 * @method static boolean num($value)
 * @method static boolean required($key, $array)
 * @method static boolean same($value, $other, $strict)
 * @method static boolean size($value, $size, $operator)
 * @method static boolean startsWith($value, $start)
 * @method static boolean time($value)
 * @method static boolean url($value)
 */
class V {}
