title: Site

tabs:
  pages:
    label: Seiten
    columns:
      left:
        width: 1/2
        sections:
          events:
            extends: sections/events
            headline: Talks
            layout: cards
            image:
              cover: true
      right:
        width: 1/2
        sections:
          pages:
            headline: Seiten
            image:
              back: blue
              color: blue-100
          listPagesModifiedByUser:
            type: recentlymodified
            headline: Zuletzt geändert
  contact:
    label: Kontakt/Social
    columns:
      left:
        width: 2/3
        fields:
          addressHeadline:
            type: headline
            label: Anschrift
          address1:
            type: text
            width: 1/2
          address2:
            type: text
            width: 1/2
          postal-code:
            type: text
            width: 1/4
          city:
            type: text
            width: 3/4
          phoneMailHeadline:
            type: headline
            label: Telefon & E-Mail
          phone:
            type: tel
            width: 1/2
          email:
            type: email
            width: 1/2
          socialHeadline:
            type: headline
            label: Social
          facebook:
            type: text
            icon: facebook
            width: 1/2
          twitter:
            type: text
            icon: twitter
            width: 1/2
      right:
        width: 1/3
        fields:
          main_image:
            extends: fields/main-image
            label: Fallback Bild für Social Media
            required: true
            image:
              cover: true
  navigation:
    fields:
      footer_navigation:
        label: Footer
        type: pages
