name: PHP Insights

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    name: PHP Insights checks
    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: 📦 Setup PHP + install deps
        uses: ./.github/actions/setup-php-composer

      - name: 🏃‍♂️ Run checks
        run: vendor/bin/phpinsights -n --ansi --format=github-action
